name: CI

on:
  push:
    branches: main

jobs:
  build:
    strategy:
      matrix:
        package: ["aws-cli-v2-bin"]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: /mnt
    container:
      image: archlinux:base-devel
      volumes:
        - /mnt:/mnt
    steps:
      - name: Checkout aur package
        run: git clone https://aur.archlinux.org/${{ matrix.package }}.git /mnt
      - name: Make Package
        run: makepkg -sic 

      - run: ls -la /mnt
