name: CI

on:
  push:
    branches: main

jobs:
  build:
    strategy:
      matrix:
        package: ["aws-cli-v2-bin"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout aur package
        uses: actions/checkout@v3
        with:
          repository: https://aur.archlinux.org/${matrix.package}.git

      - name: Validate package
        uses: hapakaien/archlinux-package-action@v2
        with:
          path: ${matrix.package}/
