name: CI

on:
  push:
    branches: main

jobs:
  build:
    strategy:
      matrix:
        package: ["aws-cli-v2-bin"]
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      volumes:
        - /mnt:/mnt
    steps:
      - run: pacman -Sy --noconfirm git
      - name: Checkout aur package
        run: git clone https://aur.archlinux.org/${{ matrix.package }}.git /mnt/package
      - name: add builder and chown
        run: useradd builder && chown builder:builder /mnt/package
      - name: Make Package
        run: su builder && cd /mnt/package && makepkg -sic 
      - run: ls -la /mnt/package
