name: CI

on:
  push:
    branches: main

jobs:
  build:
    strategy:
      matrix:
        package: ["aws-cli-v2-bin"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout aur package
        run: git clone https://aur.archlinux.org/${{ matrix.package }}.git $GITHUB_WORKSPACE

      - name: Validate package
        uses: hapakaien/archlinux-package-action@v2
        with:
          path: ${{ matrix.package }}
